### ISSUE TITLE
Move Reliability content to the Advanced Administration Handbook

### ISSUE THREAD

**Issue by javiercasares** [WordPress/hosting-handbook#152]
There is a lot of content previously added to the Hosting handbook because there was no place to include it.

Now, with the Advanced Administration Handbook, we have some duplicated content, and we need to move / mix some content into the new Handbook.

**Reliability**

The [Reliability](https://make.wordpress.org/hosting/handbook/reliability/) page can be included into the Performance and the Cache pages.

Tickets:
- [ ] Update page: Backups [#148](https://github.com/WordPress/Advanced-administration-handbook/issues/148)
- [ ] New page: Monitoring [#157](https://github.com/WordPress/Advanced-administration-handbook/issues/157)
- [ ] New page: Version Control [#158](https://github.com/WordPress/Advanced-administration-handbook/issues/158)

**Comment by kittenkamala** [comment]
It is my feeling that the team should actually do the opposite. That the Advanced Admin Handbook should be part of the Hosting Handbook.
